name: CI

on: [push, pull_request]

jobs:
  Testing:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node-version: [10.x, 12.x]
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@master

      - name: Use Node.js version ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Cache node_modules
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ matrix.node-version }}-${{ matrix.os }}-${{ hashFiles('package-lock.json') }}

      - name: Install Dependencies
        run: npm install

      - name: Test
        run: npm test
        env:
          CI: true
